In [1]:
from torch_pgd import pgd_attack
from utils import get_pretrained_model

import torch as ch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import torchvision.transforms as transforms
from Generator import SeedGenerator

import os, random
import torchvision.transforms.functional as TF
from torch.utils.data import Dataset, DataLoader

In [2]:
def tensor2pic(ImA, pop_img=False, save=False, name="pil_image.png", verbose=False):
    ImA = ImA[0].numpy()
    ImA = ImA.transpose(1, 2, 0)
    img = Image.fromarray(np.uint8(ImA * 255), 'RGB')
    if save:
        if verbose:
            print("Storing image:", name)
        img.save(name)
    if pop_img:
        img.show()
    else:
        return img

In [4]:
# Storage details
save_images = True
title = "5_"
save_path = 'Results/restrict/'
images = []

In [5]:
# Parameters
eps = 50
steps = 50
step_size = 0.2
targeted_attack = True
norm = 'l2'
verbose = False

reps = 3

In [6]:
# Models and datasets
model_name = 'RestrictedImageNet'
dataset_path = "datasets/"
datasets = ['cat2/', 'frog2/', 'bird/']
classes = [1, 2, 4]

In [7]:
_, model = get_pretrained_model(model_name)
model.eval()

for k, dataset in enumerate(datasets):
    sg = SeedGenerator(dataset_path + dataset)
    sg.load_data()
    sg.generate_dist()
    
    print(sg.sigma)
    
    print("DONE UNO")
    
    for i in range(reps):
        seed = sg.sample()
        
        tensor2pic(seed, save=True, name=save_path+title+dataset[:3]+'seed'+str(i)+".png", verbose=verbose)
        
        out_img = pgd_attack(seed, eps=eps, model=model, steps=steps, step_size=step_size, 
                            targeted_attack=targeted_attack, target_class=classes[k], 
                            norm=norm, verbose=verbose)
    
        tensor2pic(out_img, save=True, name=save_path+title+dataset[:3]+'gene'+str(i)+".png", verbose=verbose)
    

tensor([0.4615, 0.4542, 0.4609,  ..., 0.3818, 0.3837, 0.3787])
9408
tensor([[0.1002, 0.0934, 0.0893,  ..., 0.0123, 0.0142, 0.0158],
        [0.0934, 0.0979, 0.0915,  ..., 0.0118, 0.0134, 0.0147],
        [0.0893, 0.0915, 0.0961,  ..., 0.0132, 0.0152, 0.0160],
        ...,
        [0.0123, 0.0118, 0.0132,  ..., 0.0756, 0.0707, 0.0676],
        [0.0142, 0.0134, 0.0152,  ..., 0.0707, 0.0781, 0.0725],
        [0.0158, 0.0147, 0.0160,  ..., 0.0676, 0.0725, 0.0780]])
DONE UNO
tensor([0.4157, 0.4147, 0.4182,  ..., 0.3150, 0.3177, 0.3124])
9408
tensor([[0.0612, 0.0535, 0.0511,  ..., 0.0083, 0.0085, 0.0077],
        [0.0535, 0.0606, 0.0545,  ..., 0.0086, 0.0083, 0.0083],
        [0.0511, 0.0545, 0.0606,  ..., 0.0093, 0.0093, 0.0092],
        ...,
        [0.0083, 0.0086, 0.0093,  ..., 0.0575, 0.0495, 0.0448],
        [0.0085, 0.0083, 0.0093,  ..., 0.0495, 0.0593, 0.0508],
        [0.0077, 0.0083, 0.0092,  ..., 0.0448, 0.0508, 0.0588]])
DONE UNO
tensor([0.4746, 0.4684, 0.4703,  ..., 0.4097, 0.40

In [8]:
sg.mu

tensor([0.4746, 0.4684, 0.4703,  ..., 0.4097, 0.4097, 0.4141])

In [9]:
len(sg.mu)

9408

In [10]:
56*56*3

9408

In [11]:
9408**0.5

96.99484522385713